서울시에 존재하는 주유소의 1년치 휘발유 가격과 두바우 유의 상관계수 구하기

In [21]:
import io
import time
import pandas as pd
import requests
import multiprocessing

In [2]:
df = pd.read_csv("../data/상반기 주유소 판매가격.csv", encoding='cp949')

In [3]:
counts = df['번호'].value_counts()

In [4]:
numbers = counts[counts == 181].index.tolist()

In [5]:
df1 = df[df['번호'].isin(numbers)]

In [6]:
81450 / 450

181.0

In [7]:
df1.번호.unique()

<ArrowStringArray>
['A0006039', 'A0000525', 'A0001219', 'A0009061', 'A0001217', 'A0001213',
 'A0009838', 'A0010235', 'A0009710', 'A0010207',
 ...
 'A0009214', 'A0009158', 'A0004216', 'A0010071', 'A0032696', 'A0010081',
 'A0009220', 'A0009197', 'A0009180', 'A0032659']
Length: 450, dtype: str

In [12]:
df2 = df1.groupby('기간').sum().drop(['지역', '상호', '주소', '상표', '셀프여부'], axis=1)

In [13]:
df2

,번호,고급휘발유,휘발유,경유,실내등유
기간,,,,,
20190101,A0006039A0000525A0001219A0009061A0001217A00012...,321075,671197,620924,245309
20190102,A0006039A0000525A0001219A0009061A0001217A00012...,320364,669423,618994,245158
20190103,A0006039A0000525A0001219A0009061A0001217A00012...,319333,667300,617055,245071
20190104,A0006039A0000525A0001219A0009061A0001217A00012...,318966,666131,616165,243372
20190105,A0006039A0000525A0001219A0009061A0001217A00012...,316935,663851,614110,244680
...,...,...,...,...,...
20190626,A0006039A0000525A0001219A0009061A0001217A00012...,347926,716472,655960,184070
20190627,A0006039A0000525A0001219A0009061A0001217A00012...,347804,716144,655730,179356
20190628,A0006039A0000525A0001219A0009061A0001217A00012...,347690,716043,655669,178255
20190629,A0006039A0000525A0001219A0009061A0001217A00012...,347796,715913,655688,178796
20190630,A0006039A0000525A0001219A0009061A0001217A00012...,347805,715909,655579,176421

In [19]:
df3 = df2.drop(['번호'], axis=1) / 450

In [20]:
df3

               고급휘발유          휘발유           경유        실내등유
기간
20190101  713.500000  1491.548889  1379.831111  545.131111
20190102  711.920000  1487.606667  1375.542222  544.795556
20190103  709.628889  1482.888889  1371.233333  544.602222
20190104  708.813333  1480.291111  1369.255556  540.826667
20190105  704.300000  1475.224444  1364.688889  543.733333
...              ...          ...          ...         ...
20190626  773.168889  1592.160000  1457.688889  409.044444
20190627  772.897778  1591.431111  1457.177778  398.568889
20190628  772.644444  1591.206667  1457.042222  396.122222
20190629  772.880000  1590.917778  1457.084444  397.324444
20190630  772.900000  1590.908889  1456.842222  392.046667

[181 rows x 4 columns]