웹에서 정보를 requests를 사용하여 가져오는 실습<br>get과 post에 따라 방식이 달라진다.

In [1]:
import requests
import pandas as pd

In [2]:
url = "https://m.stock.naver.com/front-api/external/chart/domestic/info?symbol={}&requestType=1&startTime={}&endTime={}&timeframe=day"

In [4]:
data = eval(requests.get(url.format('005930', '20260101', '20260630')).text.strip())
df = pd.DataFrame(data[1:], columns=data[0])

df

           날짜      시가      고가      저가      종가       거래량  외국인소진율
0    20260102  120200  128500  120200  128500  30463279   52.37
1    20260105  134600  138600  133600  138100  42863376   52.40
2    20260106  135300  139300  132700  138900  45321341   52.18
3    20260107  143500  144400  137600  141000  46317413   52.22
4    20260108  138300  144500  138300  138800  41449329   52.15
..        ...     ...     ...     ...     ...       ...     ...
115  20260624  314000  341000  314000  340500  47809959   47.41
116  20260625  359500  362500  352000  358500  36157158   47.37
117  20260626  354000  356500  321500  339500  39735951   47.24
118  20260629  331000  335500  316000  323000  35436521   47.01
119  20260630  323500  343000  321000  337500  22482962   47.01

[120 rows x 7 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      120 non-null    object
 1   시가      120 non-null    int64
 2   고가      120 non-null    int64
 3   저가      120 non-null    int64
 4   종가      120 non-null    int64
 5   거래량     120 non-null    int64
 6   외국인소진율  120 non-null    float64
dtypes: float64(1), int64(5), object(1)
memory usage: 6.7+ KB

In [9]:
from datetime import datetime, date, timedelta

In [29]:
datetime.now()

datetime.datetime(2026, 6, 30, 15, 17, 20, 789557)

In [31]:
date.today() + timedelta()

datetime.date(2026, 6, 30)

In [32]:
date.today().strftime("%Y/%m/%d")

'2026/06/30'

In [69]:
payload = {
    'in_biz_cds': '0',
    'in_scodes': '0',
    'isError': 'false',
    'ins_lat': '37.56531505994446',
    'ins_lng': '126.97879417484003',
    'search_text': '',
    'p_sido_cd': '',
    'p_gugun_cd': '',
    'in_distance': '5',
    'in_biz_cd': '',
    'iend': '100',
    'searchType': 'A',
    'set_date': '',
    'all_store': '0',
    'T03': '0',
    'T01': '0',
    'T27': '0',
    'T12': '0',
    'T09': '0',
    'T30': '0',
    'T05': '0',
    'T22': '0',
    'T21': '0',
    'T36': '0',
    'T43': '0',
    'Z9999': '0',
    'T64': '0',
    'P02': '0',
    'P10': '0',
    'P50': '0',
    'P20': '0',
    'P60': '0',
    'P30': '0',
    'P70': '0',
    'P40': '0',
    'P80': '0',
    'whcroad_yn': '0',
    'P90': '0',
    'P01': '0',
    'new_bool': '0',
    'rndCod': 'W85L1Q7PLL'
}

In [70]:
starbucks = 'https://www.starbucks.co.kr/store/getStore.do?r=6BXDI6AN74'

In [71]:
starbucks_address = requests.post(starbucks, data=payload).text

In [43]:
import json

In [74]:
star_dict1 = json.loads(starbucks_address)

In [72]:
star_dict2 = requests.post(starbucks, data=payload).json()

In [75]:
star_dict1 == star_dict2

True

In [76]:
star_df = pd.DataFrame(star_dict2['list'])

In [77]:
star_df.shape

(100, 137)

In [78]:
star_df.isnull().sum()

seq           0
sido_cd     100
sido_nm     100
gugun_cd    100
gugun_nm    100
           ...
t48           0
z9999         0
t64           0
t66           0
p02           0
Length: 137, dtype: int64

In [79]:
star_df[['addr', 's_name', 'lot', 'lat']]

,addr,s_name,lot,lat
0,서울특별시 중구 소공동 87-10,환구단,126.97916226763291,37.56448620899717
1,서울특별시 중구 을지로1가 50 삼성화재 삼성빌딩1층,시청,126.979808,37.56629
2,서울특별시 중구 무교동 32-2 남강건설회관빌딩,무교로,126.97907661254083,37.56722071682264
3,서울특별시 중구 태평로1가 25 프레스센터,한국프레스센터,126.9780493948243,37.56724756017782
4,서울특별시 중구 소공동 70번지 삼영빌딩 1층일부,소공로,126.980849,37.563883
...,...,...,...,...
95,서울특별시 용산구 청파동2가 53-12 숙명여자대학교,숙명여대정문,126.9648900666431,37.54493793442227
96,서울특별시 중구 을지로6가 18-12 두산타워빌딩,동대문두타,127.00882344256042,37.56883952851115
97,"서울특별시 중구 을지로7가 2-1, B2층 F1호",동대문디자인플라자,127.00972596864787,37.56735506718157
98,서울특별시 종로구 동숭동 1-115번지 1-2층,마로니에공원,127.0023412,37.58154296
99,서울특별시 마포구 아현동 618-19 마포 센텀 슬로우스퀘어,마포경찰서후문,126.953432,37.550800